advert_height=96
adverturl=http://www.runescape.com/g=oldscape/bare_advert.ws
applet_maxheight=2160
applet_maxwidth=5760
applet_minheight=503
applet_minwidth=765
browsercontrol_win_amd64_jar=browsercontrol_1_1674545273.jar
browsercontrol_win_x86_jar=browsercontrol_0_-1928975093.jar
cachedir=oldschool
codebase=http://oldschool46.runescape.com/
download=1318935
initial_class=client.class
initial_jar=gamepack_7038031.jar
mac_sub_version=2
msg_cancel=Cancel
msg_changes_on_restart=Your changes will take effect when you next start this program.
msg_copy_paste_url=Please copy and paste the following URL into your web browser
msg_err_create_advertising=Unable to create advertising
msg_err_create_target=Unable to create target applet
msg_err_downloading=Error downloading
msg_err_get_file=Error getting file
msg_err_load_bc=Unable to load browsercontrol
msg_err_save_file=Error saving file
msg_err_verify_bc=Unable to verify browsercontrol
msg_err_verify_bc64=Unable to verify browsercontrol64
msg_information=Information
msg_lang0=English
msg_language=Language
msg_loading_app=Loading application
msg_loading_app_resources=Loading application resources
msg_message=Message
msg_new_version=Update available! You can now launch the client directly from the OldSchool website.
Get the new version from the link on the OldSchool homepage: http://oldschool.runescape.com/
msg_new_version_link=http://oldschool.runescape.com/
msg_new_version_linktext=Open OldSchool Homepage
msg_ok=OK
msg_options=Options
msg_tandc=This game is copyright Â© 1999 - 2020 Jagex Ltd.Use of this game is subject to our ["http://www.runescape.com/terms/terms.ws"Terms and Conditions] and ["http://www.runescape.com/privacy/privacy.ws"Privacy Policy].
other_sub_version=2
param_1=1
param_10=5
param_11=https://auth.jagex.com/
param_12=346
param_13=.runescape.com
param_14=0
param_15=0
param_16=false
param_17=http://www.runescape.com/g=oldscape/slr.ws?order=LPWM
param_18=
param_19=196515767263-1oo20deqm6edn7ujlihl6rpadk9drhva.apps.googleusercontent.com
param_2=https://payments.jagex.com/operator/v1/
param_3=true
param_4=41277
param_5=1
param_6=0
param_7=0
param_8=true
param_9=ElZAIrq5NpKN6D3mDdihco3oPeYN2KFy2DCquj7JMmECPmLrDP3Bnw
privacyurl=http://www.jagex.com/g=oldscape/privacy/privacy.ws
storebase=0
termsurl=http://www.jagex.com/g=oldscape/terms/terms.ws
title=Old School RuneScape
viewerversion=124
win_sub_version=1
window_preferredheight=600
window_preferredwidth=800
